Insert into places(city,region,country) values('Aardenburg','Zeeland','NL');                    ### this part is to insert city,region and country values 
Insert into places(city,region,country) values('Abbekerk','Noord-Holland','NL');
Insert into places(city,region,country) values('Alkmaar','Noord-Holland','NL');
Insert into places(city,region,country) values('Almelo','Overijssel','NL');
Insert into places(city,region,country) values('Ameide','Utrecht','NL');
Insert into places(city,region,country) values('Amersfoort','Utrecht','NL');
Insert into places(city,region,country) values('Ammerstol','Zuid-Holland','NL');
Insert into places(city,region,country) values('Amsterdam','Noord-Holland','NL');
Insert into places(city,region,country) values('Appingedam','Groningen','NL');
Insert into places(city,region,country) values('Arnemuiden','Zeeland','NL');
Insert into places(city,region,country) values('Arnhem','Gelderland','NL');
Insert into places(city,region,country) values('Asperen','Gelderland','NL');
Insert into places(city,region,country) values('Assen','Drenthe','NL');
Insert into places(city,region,country) values('Austerlitz','Utrecht','NL');
Insert into places(city,region,country) values('Axel','Zeeland','NL');
Insert into places(city,region,country) values('Baarn','Utrecht','NL');
Insert into places(city,region,country) values('Barsingerhorn','Noord-Holland','NL');
Insert into places(city,region,country) values('Haringhuizen','Noord-Holland','NL');
Insert into places(city,region,country) values('Batenburg','Gelderland','NL');
Insert into places(city,region,country) values('Bergen op Zoom','Noord-Brabant','NL');
Insert into places(city,region,country) values('Beverwijk','Noord-Holland','NL');
Insert into places(city,region,country) values('Biervliet','Zeeland','NL');
Insert into places(city,region,country) values('Bolsward','Friesland','NL');
Insert into places(city,region,country) values('Borculo','Gelderland','NL');
Insert into places(city,region,country) values('Breda','Noord-Brabant','NL');
Insert into places(city,region,country) values('Bredevoort','Gelderland','NL');
Insert into places(city,region,country) values('Brielle','Zuid-Holland','NL');
Insert into places(city,region,country) values('Bronkhorst','Gelderland','NL');
Insert into places(city,region,country) values('Brouwershaven','Zeeland','NL');
Insert into places(city,region,country) values('Bunschoten','Utrecht','NL');
Insert into places(city,region,country) values('Buren','Gelderland','NL');
Insert into places(city,region,country) values('Coevorden','Drenthe','NL');
Insert into places(city,region,country) values('Culemborg','Gelderland','NL');
Insert into places(city,region,country) values('Delden','Overijssel','NL');
Insert into places(city,region,country) values('Delft','Zuid-Holland','NL');
Insert into places(city,region,country) values('Delfzijl','Groningen','NL');
Insert into places(city,region,country) values('Deventer','Overijssel','NL');
Insert into places(city,region,country) values('Doesburg','Gelderland','NL');
Insert into places(city,region,country) values('Doetinchem','Gelderland','NL');
Insert into places(city,region,country) values('Dokkum','Friesland','NL');
Insert into places(city,region,country) values('Domburg','Zeeland','NL');
Insert into places(city,region,country) values('Dordrecht','Zuid-Holland','NL');
Insert into places(city,region,country) values('Echt','Limburg','NL');
Insert into places(city,region,country) values('Edam','Noord-Holland','NL');
Insert into places(city,region,country) values('Eembrugge','Utrecht','NL');
Insert into places(city,region,country) values('Eemnes-Binnen','Utrecht','NL');
Insert into places(city,region,country) values('Eemnes-Buiten','Utrecht','NL');
Insert into places(city,region,country) values('Eindhoven','Noord-Brabant','NL');
Insert into places(city,region,country) values('Elburg','Gelderland','NL');
Insert into places(city,region,country) values('Enkhuizen','Noord-Holland','NL');
Insert into places(city,region,country) values('Enschede','Overijssel','NL');
Insert into places(city,region,country) values('Franeker','Friesland','NL');
Insert into places(city,region,country) values('Geertruidenberg','Noord-Brabant','NL');
Insert into places(city,region,country) values('Geervliet','Zuid-Holland','NL');
Insert into places(city,region,country) values('Gendt','Gelderland','NL');
Insert into places(city,region,country) values('Genemuiden','Overijssel','NL');
Insert into places(city,region,country) values('Gennep','Limburg','NL');
Insert into places(city,region,country) values('Goedereede','Zuid-Holland','NL');
Insert into places(city,region,country) values('Goes','Zeeland','NL');
Insert into places(city,region,country) values('Goor','Overijssel','NL');
Insert into places(city,region,country) values('Gorinchem','Zuid-Holland','NL');
Insert into places(city,region,country) values('Gouda','Zuid-Holland','NL');
Insert into places(city,region,country) values('Grafhorst','Overijssel','NL');
Insert into places(city,region,country) values('Gramsbergen','Overijssel','NL');
Insert into places(city,region,country) values('Grave','Noord-Brabant','NL');
Insert into places(city,region,country) values('Groenlo','Gelderland','NL');
Insert into places(city,region,country) values('Groningen','Groningen','NL');
Insert into places(city,region,country) values('Grootebroek ','Noord-Holland','NL');
Insert into places(city,region,country) values('Haarlem','Noord-Holland','NL');
Insert into places(city,region,country) values('Haastrecht','Zuid-Holland','NL');
Insert into places(city,region,country) values('Hardenberg','Overijssel','NL');
Insert into places(city,region,country) values('Harderwijk','Gelderland','NL');
Insert into places(city,region,country) values('Harlingen','Friesland','NL');
Insert into places(city,region,country) values('Hasselt','Overijssel','NL');
Insert into places(city,region,country) values('Hattem','Gelderland','NL');
Insert into places(city,region,country) values('Heenvliet','Zuid-Holland','NL');
Insert into places(city,region,country) values('Helmond','Noord-Brabant','NL');
Insert into places(city,region,country) values('Hem','Noord-Holland','NL');
Insert into places(city,region,country) values('Heukelum','Gelderland','NL');
Insert into places(city,region,country) values('Heusden','Noord-Brabant','NL');
Insert into places(city,region,country) values('Hindeloopen','Friesland','NL');
Insert into places(city,region,country) values('Hoorn','Noord-Holland','NL');
Insert into places(city,region,country) values('Huissen','Gelderland','NL');
Insert into places(city,region,country) values('Hulst','Zeeland','NL');
Insert into places(city,region,country) values('IJlst','Friesland','NL');
Insert into places(city,region,country) values('IJsselstein','Utrecht','NL');
Insert into places(city,region,country) values('IJzendijke','Zeeland','NL');
Insert into places(city,region,country) values('Kampen','Overijssel','NL');
Insert into places(city,region,country) values('Kessel','Limburg','NL');
Insert into places(city,region,country) values('Klundert','Noord-Brabant','NL');
Insert into places(city,region,country) values('Kortgene','Zeeland','NL');
Insert into places(city,region,country) values('Laag-Keppel','Gelderland','NL');
Insert into places(city,region,country) values('Langedijk','Noord-Holland','NL');
Insert into places(city,region,country) values('Leerdam','Utrecht','NL');
Insert into places(city,region,country) values('Leeuwarden','Friesland','NL');
Insert into places(city,region,country) values('Leiden','Zuid-Holland','NL');
Insert into places(city,region,country) values('Lochem','Gelderland','NL');
Insert into places(city,region,country) values('Maasbommel','Gelderland','NL');
Insert into places(city,region,country) values('Maassluis','Zuid-Holland','NL');
Insert into places(city,region,country) values('Maastricht','Limburg','NL');
Insert into places(city,region,country) values('Medemblik','Noord-Holland','NL');
Insert into places(city,region,country) values('Megen','Noord-Brabant','NL');
Insert into places(city,region,country) values('Meppel','Drenthe','NL');
Insert into places(city,region,country) values('Middelburg','Zeeland','NL');
Insert into places(city,region,country) values('Monnickendam','Noord-Holland','NL');
Insert into places(city,region,country) values('Montfoort','Utrecht','NL');
Insert into places(city,region,country) values('Montfort','Limburg','NL');
Insert into places(city,region,country) values('Muiden','Noord-Holland','NL');
Insert into places(city,region,country) values('Naarden','Noord-Holland','NL');
Insert into places(city,region,country) values('Stede Niedorp','Noord-Holland','NL');
Insert into places(city,region,country) values('Nieuwpoort','Zuid-Holland','NL');
Insert into places(city,region,country) values('Nieuwstadt','Limburg','NL');
Insert into places(city,region,country) values('Nijkerk','Gelderland','NL');
Insert into places(city,region,country) values('Nijmegen','Gelderland','NL');
Insert into places(city,region,country) values('Oisterwijk','Noord-Brabant','NL');
Insert into places(city,region,country) values('Oldenzaal','Overijssel','NL');
Insert into places(city,region,country) values('Ommen','Overijssel','NL');
Insert into places(city,region,country) values('Oostburg','Zeeland','NL');
Insert into places(city,region,country) values('Oosterhout','Noord-Brabant','NL');
Insert into places(city,region,country) values('Ootmarsum','Overijssel','NL');
Insert into places(city,region,country) values('Oss','Noord-Brabant','NL');
Insert into places(city,region,country) values('Oudewater','Utrecht','NL');
Insert into places(city,region,country) values('Philippine','Zeeland','NL');
Insert into places(city,region,country) values('Purmerend','Noord-Holland','NL');
Insert into places(city,region,country) values('Ravenstein','Noord-Brabant','NL');
Insert into places(city,region,country) values('Reimerswaal','Zeeland','NL');
Insert into places(city,region,country) values('Rhenen','Utrecht','NL');
Insert into places(city,region,country) values('Rijssen','Overijssel','NL');
Insert into places(city,region,country) values('Roermond','Limburg','NL');
Insert into places(city,region,country) values('Rotterdam','Zuid-Holland','NL');
Insert into places(city,region,country) values('Schagen','Noord-Holland','NL');
Insert into places(city,region,country) values('Schiedam','Zuid-Holland','NL');
Insert into places(city,region,country) values('Schoonhoven','Zuid-Holland','NL');
Insert into places(city,region,country) values('s-Gravenzande','Zuid-Holland','NL');
Insert into places(city,region,country) values('s-Heerenberg','Gelderland','NL');
Insert into places(city,region,country) values('s-Hertogenbosch','Noord-Brabant','NL');
Insert into places(city,region,country) values('Sint Anna ter Muiden','Zeeland','NL');
Insert into places(city,region,country) values('Sint-Maartensdijk','Zeeland','NL');
Insert into places(city,region,country) values('Sint-Oedenrode','Noord-Brabant','NL');
Insert into places(city,region,country) values('Sittard','Limburg','NL');
Insert into places(city,region,country) values('Sloten','Friesland','NL');
Insert into places(city,region,country) values('Sluis','Zeeland','NL');
Insert into places(city,region,country) values('Sneek','Friesland','NL');
Insert into places(city,region,country) values('Staverden','Gelderland','NL');
Insert into places(city,region,country) values('Stavoren','Friesland','NL');
Insert into places(city,region,country) values('Steenbergen','Noord-Brabant','NL');
Insert into places(city,region,country) values('Steenwijk','Overijssel','NL');
Insert into places(city,region,country) values('Susteren','Limburg','NL');
Insert into places(city,region,country) values('Terborg','Gelderland','NL');
Insert into places(city,region,country) values('Terneuzen','Zeeland','NL');
Insert into places(city,region,country) values('Texel','Noord-Holland','NL');
Insert into places(city,region,country) values('Tholen','Zeeland','NL');
Insert into places(city,region,country) values('Thorn','Limburg','NL');
Insert into places(city,region,country) values('Tiel','Gelderland','NL');
Insert into places(city,region,country) values('Tilburg','Noord-Brabant','NL');
Insert into places(city,region,country) values('Utrecht','Utrecht','NL');
Insert into places(city,region,country) values('Valkenburg','Limburg','NL');
Insert into places(city,region,country) values('Veere','Zeeland','NL');
Insert into places(city,region,country) values('Venlo','Limburg','NL');
Insert into places(city,region,country) values('Vianen','Utrecht','NL');
Insert into places(city,region,country) values('Vlaardingen','Zuid-Holland','NL');
Insert into places(city,region,country) values('Vlissingen','Zeeland','NL');
Insert into places(city,region,country) values('Vollenhove','Overijssel','NL');
Insert into places(city,region,country) values('Vreeland','Utrecht','NL');
Insert into places(city,region,country) values('Waalwijk','Noord-Brabant','NL');
Insert into places(city,region,country) values('Wageningen','Gelderland','NL');
Insert into places(city,region,country) values('Weert','Limburg','NL');
Insert into places(city,region,country) values('Weesp','Noord-Holland','NL');
Insert into places(city,region,country) values('Wessem','Limburg','NL');
Insert into places(city,region,country) values('Westkapelle','Zeeland','NL');
Insert into places(city,region,country) values('Westwoud','Noord-Holland','NL');
Insert into places(city,region,country) values('Wieringen','Noord-Holland','NL');
Insert into places(city,region,country) values('Wijk bij Duurstede','Utrecht','NL');
Insert into places(city,region,country) values('Willemstad','Noord-Brabant','NL');
Insert into places(city,region,country) values('Wilsum','Overijssel','NL');
Insert into places(city,region,country) values('Winkel','Noord-Holland','NL');
Insert into places(city,region,country) values('Winschoten','Groningen','NL');
Insert into places(city,region,country) values('Woerden','Utrecht','NL');
Insert into places(city,region,country) values('Workum','Friesland','NL');
Insert into places(city,region,country) values('Woudrichem','Noord-Brabant','NL');
Insert into places(city,region,country) values('Zaandam','Noord-Holland','NL');
Insert into places(city,region,country) values('Zaltbommel','Gelderland','NL');
Insert into places(city,region,country) values('Zevenaar','Gelderland','NL');
Insert into places(city,region,country) values('Zevenbergen','Noord-Brabant','NL');
Insert into places(city,region,country) values('Zierikzee','Zeeland','NL');
Insert into places(city,region,country) values('Zutphen','Gelderland','NL');
Insert into places(city,region,country) values('Zwolle','Overijssel','NL');
UPDATE places SET population = 2520 WHERE city = 'Aardenburg';                                          ### this part is to insert population values
UPDATE places SET population = 45650 WHERE city = 'Doetinchem';
UPDATE places SET population = 11096 WHERE city = 'Doesburg';
UPDATE places SET population = 1660 WHERE city = 'Domburg';
UPDATE places SET population = 14675 WHERE city = 'Echt';
UPDATE places SET population = 12745 WHERE city = 'Dokkum';
UPDATE places SET population = 6900 WHERE city = 'Edam';
UPDATE places SET population = 9407 WHERE city = 'Eemnes';
UPDATE places SET population = 119146 WHERE city = 'Dordrecht';
UPDATE places SET population = 81545 WHERE city = 'Deventer';
UPDATE places SET population = 7390 WHERE city = 'Delden';
UPDATE places SET population = 103322 WHERE city = 'Delft';
UPDATE places SET population = 29302 WHERE city = 'Culemborg';
UPDATE places SET population = 11630 WHERE city = 'Zierikzee';
UPDATE places SET population = 35455 WHERE city = 'Coevorden';
UPDATE places SET population = 39705 WHERE city = 'Zutphen';
UPDATE places SET population = 14530 WHERE city = 'Zevenbergen';
UPDATE places SET population = 130173 WHERE city = 'Zwolle';
UPDATE places SET population = 13070 WHERE city = 'Zaltbommel';
UPDATE places SET population = 25855 WHERE city = 'Zevenaar';
UPDATE places SET population = 78705 WHERE city = 'Zaandam';
UPDATE places SET population = 4680 WHERE city = 'Woudrichem';
UPDATE places SET population = 3400 WHERE city = 'Winkel';
UPDATE places SET population = 4475 WHERE city = 'Workum';
UPDATE places SET population = 52851 WHERE city = 'Woerden';
UPDATE places SET population = 17750 WHERE city = 'Winschoten';
UPDATE places SET population = 870 WHERE city = 'Wilsum';
UPDATE places SET population = 23887 WHERE city = 'Wijk bij Duurstede';
UPDATE places SET population = 2030 WHERE city = 'Wessem';
UPDATE places SET population = 20546 WHERE city = 'Weesp';
UPDATE places SET population = 1815 WHERE city = 'Westwoud';
UPDATE places SET population = 2630 WHERE city = 'Westkapelle';
UPDATE places SET population = 39204 WHERE city = 'Wageningen';
UPDATE places SET population = 1875 WHERE city = 'Vreeland';
UPDATE places SET population = 33880 WHERE city = 'Waalwijk';
UPDATE places SET population = 44875 WHERE city = 'Weert';
UPDATE places SET population = 74124 WHERE city = 'Vlaardingen';
UPDATE places SET population = 44264 WHERE city = 'Vlissingen';
UPDATE places SET population = 4295 WHERE city = 'Vollenhove';
UPDATE places SET population = 16455 WHERE city = 'Vianen';
UPDATE places SET population = 68575 WHERE city = 'Venlo';
UPDATE places SET population = 10500 WHERE city = 'Valkenburg';
UPDATE places SET population = 2490 WHERE city = 'Thorn';
UPDATE places SET population = 41932 WHERE city = 'Tiel';
UPDATE places SET population = 199185 WHERE city = 'Tilburg';
UPDATE places SET population = 8175 WHERE city = 'Tholen';
UPDATE places SET population = 13733 WHERE city = 'Texel';
UPDATE places SET population = 25405 WHERE city = 'Terneuzen';
UPDATE places SET population = 358974 WHERE city = 'Utrecht';
UPDATE places SET population = 4690 WHERE city = 'Terborg';
UPDATE places SET population = 17115 WHERE city = 'Steenwijk';
UPDATE places SET population = 7995 WHERE city = 'Susteren';
UPDATE places SET population = 13340 WHERE city = 'Steenbergen';
UPDATE places SET population = 965 WHERE city = 'Stavoren';
UPDATE places SET population = 30 WHERE city = 'Staverden';
UPDATE places SET population = 2350 WHERE city = 'Sluis';
UPDATE places SET population = 33590 WHERE city = 'Sneek';
UPDATE places SET population = 710 WHERE city = 'Sloten';
UPDATE places SET population = 36895 WHERE city = 'Sittard';
UPDATE places SET population = 18360 WHERE city = 'Sint-Oedenrode';
UPDATE places SET population = 3440 WHERE city = 'Sint-Maartensdijk';
UPDATE places SET population = 50 WHERE city = 'Sint Anna ter Muiden';
UPDATE places SET population = 13230 WHERE city = 'Schoonhoven';
UPDATE places SET population = 79393 WHERE city = 'Schiedam';
UPDATE places SET population = 19025 WHERE city = 'Schagen';
UPDATE places SET population = 28815 WHERE city = 'Rijssen';
UPDATE places SET population = 20220 WHERE city = 'Rhenen';
UPDATE places SET population = 41975 WHERE city = 'Roermond';
UPDATE places SET population = 3060 WHERE city = 'Ravenstein';
UPDATE places SET population = 588490 WHERE city = 'Rotterdam';
UPDATE places SET population = 2085 WHERE city = 'Philippine';
UPDATE places SET population = 10143 WHERE city = 'Oudewater';
UPDATE places SET population = 58550 WHERE city = 'Oss';
UPDATE places SET population = 4455 WHERE city = 'Ootmarsum';
UPDATE places SET population = 50720 WHERE city = 'Oosterhout';
UPDATE places SET population = 4650 WHERE city = 'Oostburg';
UPDATE places SET population = 12835 WHERE city = 'Ommen';
UPDATE places SET population = 20210 WHERE city = 'Oisterwijk';
UPDATE places SET population = 31692 WHERE city = 'Oldenzaal';
UPDATE places SET population = 29900 WHERE city = 'Nijkerk';
UPDATE places SET population = 3260 WHERE city = 'Nieuwstadt';
UPDATE places SET population = 1410 WHERE city = 'Nieuwpoort';
UPDATE places SET population = 17555 WHERE city = 'Naarden';
UPDATE places SET population = 3130 WHERE city = 'Montfort';
UPDATE places SET population = 4055 WHERE city = 'Muiden';
UPDATE places SET population = 177605 WHERE city = 'Nijmegen';
UPDATE places SET population = 42190 WHERE city = 'Middelburg';
UPDATE places SET population = 9440 WHERE city = 'Monnickendam';
UPDATE places SET population = 13868 WHERE city = 'Montfoort';
UPDATE places SET population = 34506 WHERE city = 'Meppel';
UPDATE places SET population = 8505 WHERE city = 'Medemblik';
UPDATE places SET population = 33696 WHERE city = 'Maassluis';
UPDATE places SET population = 1740 WHERE city = 'Megen';
UPDATE places SET population = 1345 WHERE city = 'Maasbommel';
UPDATE places SET population = 13545 WHERE city = 'Lochem';
UPDATE places SET population = 119447 WHERE city = 'Maastricht';
UPDATE places SET population = 580 WHERE city = 'Laag-Keppel';
UPDATE places SET population = 1910 WHERE city = 'Kortgene';
UPDATE places SET population = 18945 WHERE city = 'Leerdam';
UPDATE places SET population = 124428 WHERE city = 'Leiden';
UPDATE places SET population = 93765 WHERE city = 'Leeuwarden';
UPDATE places SET population = 5890 WHERE city = 'Klundert';
UPDATE places SET population = 4155 WHERE city = 'Kessel';
UPDATE places SET population = 37595 WHERE city = 'Kampen';
UPDATE places SET population = 33684 WHERE city = 'IJsselstein';
UPDATE places SET population = 2470 WHERE city = 'IJzendijke';
UPDATE places SET population = 10985 WHERE city = 'Hulst';
UPDATE places SET population = 850 WHERE city = 'Hindeloopen';
UPDATE places SET population = 3015 WHERE city = 'IJlst';
UPDATE places SET population = 19570 WHERE city = 'Huissen';
UPDATE places SET population = 73769 WHERE city = 'Hoorn';
UPDATE places SET population = 1325 WHERE city = 'Heusden';
UPDATE places SET population = 2280 WHERE city = 'Heukelum';
UPDATE places SET population = 1550 WHERE city = 'Hem';
UPDATE places SET population = 2475 WHERE city = 'Heenvliet';
UPDATE places SET population = 92979 WHERE city = 'Helmond';
UPDATE places SET population = 12273 WHERE city = 'Hattem';
UPDATE places SET population = 7385 WHERE city = 'Hasselt';
UPDATE places SET population = 14810 WHERE city = 'Harlingen';
UPDATE places SET population = 48739 WHERE city = 'Harderwijk';
UPDATE places SET population = 4370 WHERE city = 'Haastrecht';
UPDATE places SET population = 19675 WHERE city = 'Hardenberg';
UPDATE places SET population = 9860 WHERE city = 'Groenlo';
UPDATE places SET population = 8580 WHERE city = 'Grave';
UPDATE places SET population = 3180 WHERE city = 'Gramsbergen';
UPDATE places SET population = 1030 WHERE city = 'Grafhorst';
UPDATE places SET population = 162177 WHERE city = 'Haarlem';
UPDATE places SET population = 37456 WHERE city = 'Gorinchem';
UPDATE places SET population = 202900 WHERE city = 'Groningen';
UPDATE places SET population = 12155 WHERE city = 'Goor';
UPDATE places SET population = 28770 WHERE city = 'Goes';
UPDATE places SET population = 73936 WHERE city = 'Gouda';
UPDATE places SET population = 2295 WHERE city = 'Goedereede';
UPDATE places SET population = 9285 WHERE city = 'Gennep';
UPDATE places SET population = 10370 WHERE city = 'Genemuiden';
UPDATE places SET population = 7285 WHERE city = 'Gendt';
UPDATE places SET population = 7035 WHERE city = 'Geertruidenberg';
UPDATE places SET population = 1620 WHERE city = 'Geervliet';
UPDATE places SET population = 12780 WHERE city = 'Franeker';
UPDATE places SET population = 18632 WHERE city = 'Enkhuizen';
UPDATE places SET population = 159369 WHERE city = 'Enschede';
UPDATE places SET population = 12275 WHERE city = 'Elburg';
UPDATE places SET population = 235923 WHERE city = 'Eindhoven';
UPDATE places SET population = 2620 WHERE city = 'Buren';
UPDATE places SET population = 22186 WHERE city = 'Bunschoten';
UPDATE places SET population = 90 WHERE city = 'Bronkhorst';
UPDATE places SET population = 1250 WHERE city = 'Brouwershaven';
UPDATE places SET population = 150210 WHERE city = 'Breda';
UPDATE places SET population = 7775 WHERE city = 'Borculo';
UPDATE places SET population = 10085 WHERE city = 'Bolsward';
UPDATE places SET population = 1550 WHERE city = 'Biervliet';
UPDATE places SET population = 1450 WHERE city = 'Bredevoort';
UPDATE places SET population = 17549 WHERE city = 'Brielle';
UPDATE places SET population = 41962 WHERE city = 'Beverwijk';
UPDATE places SET population = 650 WHERE city = 'Batenburg';
UPDATE places SET population = 195 WHERE city = 'Barsingerhorn-Haringhuizen';
UPDATE places SET population = 53245 WHERE city = 'Bergen op Zoom';
UPDATE places SET population = 24765 WHERE city = 'Baarn';
UPDATE places SET population = 3095 WHERE city = 'Willemstad';
UPDATE places SET population = 130 WHERE city = 'Eembrugge';
UPDATE places SET population = 9407 WHERE city = 'Eemnes-Binnen';
UPDATE places SET population = 9407 WHERE city = 'Eemnes-Buiten';
UPDATE places SET population = 22425 WHERE city = 's-Gravenzande';
UPDATE places SET population = 8635 WHERE city = 's-Heerenberg';
UPDATE places SET population = 111025 WHERE city = 's-Hertogenbosch';
UPDATE places SET population = 7880 WHERE city = 'Axel';
UPDATE places SET population = 1625 WHERE city = 'Veere';
UPDATE places SET population = 1705 WHERE city = 'Austerlitz';
UPDATE places SET population = 69011 WHERE city = 'Assen';
UPDATE places SET population = 3205 WHERE city = 'Asperen';
UPDATE places SET population = 5360 WHERE city = 'Arnemuiden';
UPDATE places SET population = 163072 WHERE city = 'Arnhem';
UPDATE places SET population = 1715 WHERE city = 'Ammerstol';
UPDATE places SET population = 3880 WHERE city = 'Ameide';
UPDATE places SET population = 73108 WHERE city = 'Almelo';
UPDATE places SET population = 157871 WHERE city = 'Amersfoort';
UPDATE places SET population = 91035 WHERE city = 'Alkmaar';
UPDATE places SET population = 871873 WHERE city = 'Amsterdam';
UPDATE places SET population = 2070 WHERE city = 'Abbekerk';
UPDATE places SET population = 195 WHERE city = 'Haringhuizen';
UPDATE places SET population = 8585 WHERE city = 'Wieringen';
Insert into places(city,region,population,country) values('New York','New York',8804190,'USA');            ### this part is to insert city,region and country values
Insert into places(city,region,population,country) values('Los Angeles','California',3898747,'USA');
Insert into places(city,region,population,country) values('Chicago','Illinois',2746388,'USA');
Insert into places(city,region,population,country) values('Houston','Texas',2304580,'USA');
Insert into places(city,region,population,country) values('Phoenix','Arizona',1608139,'USA');
Insert into places(city,region,population,country) values('San Antonio','Texas',1434625,'USA');
Insert into places(city,region,population,country) values('San Diego','California',1386932,'USA');
Insert into places(city,region,population,country) values('Dallas','Texas',1304379,'USA');
Insert into places(city,region,population,country) values('San Jose','California',1013240,'USA');
Insert into places(city,region,population,country) values('Austin','Texas',961855,'USA');
Insert into places(city,region,population,country) values('Fort Worth','Texas',918915,'USA');
Insert into places(city,region,population,country) values('Columbus','Ohio',905748,'USA');
Insert into places(city,region,population,country) values('Charlotte','North Carolina',874579,'USA');
Insert into places(city,region,population,country) values('Seattle','Washington',737015,'USA');
Insert into places(city,region,population,country) values('Oklahoma City','Oklahoma',681054,'USA');
Insert into places(city,region,population,country) values('El Paso','Texas',678815,'USA');
Insert into places(city,region,population,country) values('Boston','Massachusetts',675647,'USA');
Insert into places(city,region,population,country) values('Portland','Oregon',652503,'USA');
Insert into places(city,region,population,country) values('Las Vegas','Nevada',641903,'USA');
Insert into places(city,region,population,country) values('Detroit','Michigan',639111,'USA');
Insert into places(city,region,population,country) values('Memphis','Tennessee',633104,'USA');
Insert into places(city,region,population,country) values('Milwaukee','Wisconsin',577222,'USA');
Insert into places(city,region,population,country) values('Albuquerque','New Mexico',564559,'USA');
Insert into places(city,region,population,country) values('Tucson','Arizona',542629,'USA');
Insert into places(city,region,population,country) values('Fresno','California',542107,'USA');
Insert into places(city,region,population,country) values('Sacramento','California',524943,'USA');
Insert into places(city,region,population,country) values('Kansas City','Missouri',508090,'USA');
Insert into places(city,region,population,country) values('Mesa','Arizona',504258,'USA');
Insert into places(city,region,population,country) values('Atlanta','Georgia',498715,'USA');
Insert into places(city,region,population,country) values('Omaha','Nebraska',486051,'USA');
Insert into places(city,region,population,country) values('Colorado Springs','Colorado',478961,'USA');
Insert into places(city,region,population,country) values('Raleigh','North Carolina',467665,'USA');
Insert into places(city,region,population,country) values('Long Beach','California',466742,'USA');
Insert into places(city,region,population,country) values('Miami','Florida',442241,'USA');
Insert into places(city,region,population,country) values('Oakland','California',440646,'USA');
Insert into places(city,region,population,country) values('Minneapolis','Minnesota',429954,'USA');
Insert into places(city,region,population,country) values('Tulsa','Oklahoma',413066,'USA');
Insert into places(city,region,population,country) values('Bakersfield','California',403455,'USA');
Insert into places(city,region,population,country) values('Wichita','Kansas',397532,'USA');
Insert into places(city,region,population,country) values('Arlington','Texas',394266,'USA');
Insert into places(city,region,population,country) values('Aurora','Colorado',386261,'USA');
Insert into places(city,region,population,country) values('Tampa','Florida',384959,'USA');
Insert into places(city,region,population,country) values('Cleveland','Ohio',372624,'USA');
Insert into places(city,region,population,country) values('Anaheim','California',346824,'USA');
Insert into places(city,region,population,country) values('Stockton','California',320804,'USA');
Insert into places(city,region,population,country) values('Corpus Christi','Texas',317863,'USA');
Insert into places(city,region,population,country) values('Henderson','Nevada',317610,'USA');
Insert into places(city,region,population,country) values('Riverside','California',314998,'USA');
Insert into places(city,region,population,country) values('Newark','New Jersey',311549,'USA');
Insert into places(city,region,population,country) values('Saint Paul','Minnesota',311527,'USA');
Insert into places(city,region,population,country) values('Santa Ana','California',310227,'USA');
Insert into places(city,region,population,country) values('Cincinnati','Ohio',309317,'USA');
Insert into places(city,region,population,country) values('Irvine','California',307670,'USA');
Insert into places(city,region,population,country) values('Orlando','Florida',307573,'USA');
Insert into places(city,region,population,country) values('Pittsburgh','Pennsylvania',302971,'USA');
Insert into places(city,region,population,country) values('Greensboro','North Carolina',299035,'USA');
Insert into places(city,region,population,country) values('Jersey City','New Jersey',292449,'USA');
Insert into places(city,region,population,country) values('Lincoln','Nebraska',291082,'USA');
Insert into places(city,region,population,country) values('Plano','Texas',285494,'USA');
Insert into places(city,region,population,country) values('Durham','North Carolina',283506,'USA');
Insert into places(city,region,population,country) values('Buffalo','New York',278349,'USA');
Insert into places(city,region,population,country) values('Chandler','Arizona',275987,'USA');
Insert into places(city,region,population,country) values('Chula Vista','California',275487,'USA');
Insert into places(city,region,population,country) values('Toledo','Ohio',270871,'USA');
Insert into places(city,region,population,country) values('Madison','Wisconsin',269840,'USA');
Insert into places(city,region,population,country) values('Reno','Nevada',264165,'USA');
Insert into places(city,region,population,country) values('Fort Wayne','Indiana',263886,'USA');
Insert into places(city,region,population,country) values('North Las Vegas','Nevada',262527,'USA');
Insert into places(city,region,population,country) values('St. Petersburg','Florida',258308,'USA');
Insert into places(city,region,population,country) values('Lubbock','Texas',257141,'USA');
Insert into places(city,region,population,country) values('Irving','Texas',256684,'USA');
Insert into places(city,region,population,country) values('Laredo','Texas',255205,'USA');
Insert into places(city,region,population,country) values('Winston–Salem','North Carolina',249545,'USA');
Insert into places(city,region,population,country) values('Glendale','Arizona',248325,'USA');
Insert into places(city,region,population,country) values('Garland','Texas',246018,'USA');
Insert into places(city,region,population,country) values('Scottsdale','Arizona',241361,'USA');
Insert into places(city,region,population,country) values('Fremont','California',230504,'USA');
Insert into places(city,region,population,country) values('Spokane','Washington',228989,'USA');
Insert into places(city,region,population,country) values('Santa Clarita','California',228673,'USA');
Insert into places(city,region,population,country) values('Hialeah','Florida',223109,'USA');
Insert into places(city,region,population,country) values('San Bernardino','California',222101,'USA');
Insert into places(city,region,population,country) values('Tacoma','Washington',219346,'USA');
Insert into places(city,region,population,country) values('Modesto','California',218464,'USA');
Insert into places(city,region,population,country) values('Huntsville','Alabama',215006,'USA');
Insert into places(city,region,population,country) values('Des Moines','Iowa',214133,'USA');
Insert into places(city,region,population,country) values('Yonkers','New York',211569,'USA');
Insert into places(city,region,population,country) values('Rochester','New York',211328,'USA');
Insert into places(city,region,population,country) values('Moreno Valley','California',208634,'USA');
Insert into places(city,region,population,country) values('Fayetteville','North Carolina',208501,'USA');
Insert into places(city,region,population,country) values('Fontana','California',208393,'USA');
Insert into places(city,region,population,country) values('Worcester','Massachusetts',206518,'USA');
Insert into places(city,region,population,country) values('Port St. Lucie','Florida',204851,'USA');
Insert into places(city,region,population,country) values('Little Rock','Arkansas',202591,'USA');
Insert into places(city,region,population,country) values('Oxnard','California',202063,'USA');
Insert into places(city,region,population,country) values('Birmingham','Alabama',200733,'USA');
Insert into places(city,region,population,country) values('Montgomery','Alabama',200603,'USA');
Insert into places(city,region,population,country) values('Frisco','Texas',200509,'USA');
Insert into places(city,region,population,country) values('Amarillo','Texas',200393,'USA');
Insert into places(city,region,population,country) values('Salt Lake City','Utah',199723,'USA');
Insert into places(city,region,population,country) values('Grand Rapids','Michigan',198917,'USA');
Insert into places(city,region,population,country) values('Huntington Beach','California',198711,'USA');
Insert into places(city,region,population,country) values('Overland Park','Kansas',197238,'USA');
Insert into places(city,region,population,country) values('Glendale','California',196543,'USA');
Insert into places(city,region,population,country) values('Tallahassee','Florida',196169,'USA');
Insert into places(city,region,population,country) values('Grand Prairie','Texas',196100,'USA');
Insert into places(city,region,population,country) values('McKinney','Texas',195308,'USA');
Insert into places(city,region,population,country) values('Cape Coral','Florida',194016,'USA');
Insert into places(city,region,population,country) values('Sioux Falls','South Dakota',192517,'USA');
Insert into places(city,region,population,country) values('Peoria','Arizona',190985,'USA');
Insert into places(city,region,population,country) values('Providence','Rhode Island',190934,'USA');
Insert into places(city,region,population,country) values('Vancouver','Washington',190915,'USA');
Insert into places(city,region,population,country) values('Knoxville','Tennessee',190740,'USA');
Insert into places(city,region,population,country) values('Akron','Ohio',190469,'USA');
Insert into places(city,region,population,country) values('Shreveport','Louisiana',187593,'USA');
Insert into places(city,region,population,country) values('Mobile','Alabama',187041,'USA');
Insert into places(city,region,population,country) values('Brownsville','Texas',186738,'USA');
Insert into places(city,region,population,country) values('Fort Lauderdale','Florida',182760,'USA');
Insert into places(city,region,population,country) values('Chattanooga','Tennessee',181099,'USA');
Insert into places(city,region,population,country) values('Tempe','Arizona',180587,'USA');
Insert into places(city,region,population,country) values('Aurora','Illinois',180542,'USA');
Insert into places(city,region,population,country) values('Santa Rosa','California',178127,'USA');
Insert into places(city,region,population,country) values('Eugene','Oregon',176654,'USA');
Insert into places(city,region,population,country) values('Elk Grove','California',176124,'USA');
Insert into places(city,region,population,country) values('Salem','Oregon',175535,'USA');
Insert into places(city,region,population,country) values('Ontario','California',175265,'USA');
Insert into places(city,region,population,country) values('Rancho Cucamonga','California',174453,'USA');
Insert into places(city,region,population,country) values('Oceanside','California',174068,'USA');
Insert into places(city,region,population,country) values('Lancaster','California',173516,'USA');
Insert into places(city,region,population,country) values('Garden Grove','California',171949,'USA');
Insert into places(city,region,population,country) values('Pembroke Pines','Florida',171178,'USA');
Insert into places(city,region,population,country) values('Fort Collins','Colorado',169810,'USA');
Insert into places(city,region,population,country) values('Palmdale','California',169450,'USA');
Insert into places(city,region,population,country) values('Springfield','Missouri',169176,'USA');
Insert into places(city,region,population,country) values('Clarksville','Tennessee',166722,'USA');
Insert into places(city,region,population,country) values('Salinas','California',163542,'USA');
Insert into places(city,region,population,country) values('Hayward','California',162954,'USA');
Insert into places(city,region,population,country) values('Paterson','New Jersey',159732,'USA');
Insert into places(city,region,population,country) values('Corona','California',157136,'USA');
Insert into places(city,region,population,country) values('Lakewood','Colorado',155984,'USA');
Insert into places(city,region,population,country) values('Springfield','Massachusetts',155929,'USA');
Insert into places(city,region,population,country) values('Sunnyvale','California',155805,'USA');
Insert into places(city,region,population,country) values('Jackson','Mississippi',153701,'USA');
Insert into places(city,region,population,country) values('Killeen','Texas',153095,'USA');
Insert into places(city,region,population,country) values('Hollywood','Florida',153067,'USA');
Insert into places(city,region,population,country) values('Murfreesboro','Tennessee',152769,'USA');
Insert into places(city,region,population,country) values('Pasadena','Texas',151950,'USA');
Insert into places(city,region,population,country) values('Bellevue','Washington',151854,'USA');
Insert into places(city,region,population,country) values('Pomona','California',151713,'USA');
Insert into places(city,region,population,country) values('Escondido','California',151038,'USA');
Insert into places(city,region,population,country) values('Joliet','Illinois',150362,'USA');
Insert into places(city,region,population,country) values('Charleston','South Carolina',150227,'USA');
Insert into places(city,region,population,country) values('Mesquite','Texas',150108,'USA');
Insert into places(city,region,population,country) values('Naperville','Illinois',149540,'USA');
Insert into places(city,region,population,country) values('Rockford','Illinois',148655,'USA');
Insert into places(city,region,population,country) values('Bridgeport','Connecticut',148654,'USA');
Insert into places(city,region,population,country) values('Syracuse','New York',148620,'USA');
Insert into places(city,region,population,country) values('Savannah','Georgia',147780,'USA');
Insert into places(city,region,population,country) values('Roseville','California',147773,'USA');
Insert into places(city,region,population,country) values('Torrance','California',147067,'USA');
Insert into places(city,region,population,country) values('Fullerton','California',143617,'USA');
Insert into places(city,region,population,country) values('Surprise','Arizona',143148,'USA');
Insert into places(city,region,population,country) values('McAllen','Texas',142210,'USA');
Insert into places(city,region,population,country) values('Thornton','Colorado',141867,'USA');
Insert into places(city,region,population,country) values('Visalia','California',141384,'USA');
Insert into places(city,region,population,country) values('Olathe','Kansas',141290,'USA');
Insert into places(city,region,population,country) values('Gainesville','Florida',141085,'USA');
Insert into places(city,region,population,country) values('West Valley City','Utah',140230,'USA');
Insert into places(city,region,population,country) values('Orange','California',139911,'USA');
Insert into places(city,region,population,country) values('Denton','Texas',139869,'USA');
Insert into places(city,region,population,country) values('Warren','Michigan',139387,'USA');
Insert into places(city,region,population,country) values('Pasadena','California',138699,'USA');
Insert into places(city,region,population,country) values('Waco','Texas',138486,'USA');
Insert into places(city,region,population,country) values('Cedar Rapids','Iowa',137710,'USA');
Insert into places(city,region,population,country) values('Dayton','Ohio',137644,'USA');
Insert into places(city,region,population,country) values('Elizabeth','New Jersey',137298,'USA');
Insert into places(city,region,population,country) values('Columbia','South Carolina',136632,'USA');
Insert into places(city,region,population,country) values('Kent','Washington',136588,'USA');
Insert into places(city,region,population,country) values('Stamford','Connecticut',135470,'USA');
Insert into places(city,region,population,country) values('Lakewood','New Jersey',135158,'USA');
Insert into places(city,region,population,country) values('Victorville','California',134810,'USA');
Insert into places(city,region,population,country) values('Miramar','Florida',134721,'USA');
Insert into places(city,region,population,country) values('Coral Springs','Florida',134394,'USA');
Insert into places(city,region,population,country) values('Sterling Heights','Michigan',134346,'USA');
Insert into places(city,region,population,country) values('New Haven','Connecticut',134023,'USA');
Insert into places(city,region,population,country) values('Carrollton','Texas',133434,'USA');
Insert into places(city,region,population,country) values('Midland','Texas',132524,'USA');
Insert into places(city,region,population,country) values('Norman','Oklahoma',128026,'USA');
Insert into places(city,region,population,country) values('Santa Clara','California',127647,'USA');
Insert into places(city,region,population,country) values('Thousand Oaks','California',126966,'USA');
Insert into places(city,region,population,country) values('Topeka','Kansas',126587,'USA');
Insert into places(city,region,population,country) values('Simi Valley','California',126356,'USA');
Insert into places(city,region,population,country) values('Columbia','Missouri',126254,'USA');
Insert into places(city,region,population,country) values('Vallejo','California',126090,'USA');
Insert into places(city,region,population,country) values('Fargo','North Dakota',125990,'USA');
Insert into places(city,region,population,country) values('Allentown','Pennsylvania',125845,'USA');
Insert into places(city,region,population,country) values('Pearland','Texas',125828,'USA');
Insert into places(city,region,population,country) values('Concord','California',125410,'USA');
Insert into places(city,region,population,country) values('Abilene','Texas',125182,'USA');
Insert into places(city,region,population,country) values('Arvada','Colorado',124402,'USA');
Insert into places(city,region,population,country) values('Berkeley','California',124321,'USA');
Insert into places(city,region,population,country) values('Ann Arbor','Michigan',123851,'USA');
Insert into places(city,region,population,country) values('Independence','Missouri',123011,'USA');
Insert into places(city,region,population,country) values('Rochester','Minnesota',121395,'USA');
Insert into places(city,region,population,country) values('Hartford','Connecticut',121054,'USA');
Insert into places(city,region,population,country) values('College Station','Texas',120511,'USA');
Insert into places(city,region,population,country) values('Clovis','California',120124,'USA');
Insert into places(city,region,population,country) values('Fairfield','California',119881,'USA');
Insert into places(city,region,population,country) values('Palm Bay','Florida',119760,'USA');
Insert into places(city,region,population,country) values('Richardson','Texas',119469,'USA');
Insert into places(city,region,population,country) values('Round Rock','Texas',119468,'USA');
Insert into places(city,region,population,country) values('Cambridge','Massachusetts',118403,'USA');
Insert into places(city,region,population,country) values('Meridian','Idaho',117635,'USA');
Insert into places(city,region,population,country) values('West Palm Beach','Florida',117415,'USA');
Insert into places(city,region,population,country) values('Evansville','Indiana',117298,'USA');
Insert into places(city,region,population,country) values('Clearwater','Florida',117292,'USA');
Insert into places(city,region,population,country) values('Billings','Montana',117116,'USA');
Insert into places(city,region,population,country) values('West Jordan','Utah',116961,'USA');
Insert into places(city,region,population,country) values('Richmond','California',116448,'USA');
Insert into places(city,region,population,country) values('Westminster','Colorado',116317,'USA');
Insert into places(city,region,population,country) values('Manchester','New Hampshire',115644,'USA');
Insert into places(city,region,population,country) values('Lowell','Massachusetts',115554,'USA');
Insert into places(city,region,population,country) values('Wilmington','North Carolina',115451,'USA');
Insert into places(city,region,population,country) values('Antioch','California',115291,'USA');
Insert into places(city,region,population,country) values('Beaumont','Texas',115282,'USA');
Insert into places(city,region,population,country) values('Provo','Utah',115162,'USA');
Insert into places(city,region,population,country) values('North Charleston','South Carolina',114852,'USA');
Insert into places(city,region,population,country) values('Elgin','Illinois',114797,'USA');
Insert into places(city,region,population,country) values('Carlsbad','California',114746,'USA');
Insert into places(city,region,population,country) values('Odessa','Texas',114428,'USA');
Insert into places(city,region,population,country) values('Waterbury','Connecticut',114403,'USA');
Insert into places(city,region,population,country) values('Springfield','Illinois',114394,'USA');
Insert into places(city,region,population,country) values('League City','Texas',114392,'USA');
Insert into places(city,region,population,country) values('Downey','California',114355,'USA');
Insert into places(city,region,population,country) values('Gresham','Oregon',114247,'USA');
Insert into places(city,region,population,country) values('High Point','North Carolina',114059,'USA');
Insert into places(city,region,population,country) values('Broken Arrow','Oklahoma',113540,'USA');
Insert into places(city,region,population,country) values('Peoria','Illinois',113150,'USA');
Insert into places(city,region,population,country) values('Lansing','Michigan',112644,'USA');
Insert into places(city,region,population,country) values('Lakeland','Florida',112641,'USA');
Insert into places(city,region,population,country) values('Pompano Beach','Florida',112046,'USA');
Insert into places(city,region,population,country) values('Costa Mesa','California',111918,'USA');
Insert into places(city,region,population,country) values('Pueblo','Colorado',111876,'USA');
Insert into places(city,region,population,country) values('Lewisville','Texas',111822,'USA');
Insert into places(city,region,population,country) values('Miami Gardens','Florida',111640,'USA');
Insert into places(city,region,population,country) values('Las Cruces','New Mexico',111385,'USA');
Insert into places(city,region,population,country) values('Sugar Land','Texas',111026,'USA');
Insert into places(city,region,population,country) values('Murrieta','California',110949,'USA');
Insert into places(city,region,population,country) values('Everett','Washington',110629,'USA');
Insert into places(city,region,population,country) values('Temecula','California',110003,'USA');
Insert into places(city,region,population,country) values('Dearborn','Michigan',109976,'USA');
Insert into places(city,region,population,country) values('Santa Maria','California',109707,'USA');
Insert into places(city,region,population,country) values('West Covina','California',109501,'USA');
Insert into places(city,region,population,country) values('El Monte','California',109450,'USA');
Insert into places(city,region,population,country) values('Greeley','Colorado',108795,'USA');
Insert into places(city,region,population,country) values('Sparks','Nevada',108445,'USA');
Insert into places(city,region,population,country) values('Centennial','Colorado',108418,'USA');
Insert into places(city,region,population,country) values('Boulder','Colorado',108250,'USA');
Insert into places(city,region,population,country) values('Sandy Springs','Georgia',108080,'USA');
Insert into places(city,region,population,country) values('Inglewood','California',107762,'USA');
Insert into places(city,region,population,country) values('Edison','New Jersey',107588,'USA');
Insert into places(city,region,population,country) values('South Fulton','Georgia',107436,'USA');
Insert into places(city,region,population,country) values('Green Bay','Wisconsin',107395,'USA');
Insert into places(city,region,population,country) values('Burbank','California',107337,'USA');
Insert into places(city,region,population,country) values('Renton','Washington',106785,'USA');
Insert into places(city,region,population,country) values('Hillsboro','Oregon',106447,'USA');
Insert into places(city,region,population,country) values('El Cajon','California',106215,'USA');
Insert into places(city,region,population,country) values('Tyler','Texas',105995,'USA');
Insert into places(city,region,population,country) values('San Mateo','California',105661,'USA');
Insert into places(city,region,population,country) values('Brockton','Massachusetts',105643,'USA');
Insert into places(city,region,population,country) values('Concord','North Carolina',105240,'USA');
Insert into places(city,region,population,country) values('Daly City','California',104901,'USA');
Insert into places(city,region,population,country) values('Allen','Texas',104627,'USA');
Insert into places(city,region,population,country) values('Rio Rancho','New Mexico',104046,'USA');
Insert into places(city,region,population,country) values('Rialto','California',104026,'USA');
Insert into places(city,region,population,country) values('Woodbridge','New Jersey',103639,'USA');
Insert into places(city,region,population,country) values('South Bend','Indiana',103453,'USA');
Insert into places(city,region,population,country) values('Spokane Valley','Washington',102976,'USA');
Insert into places(city,region,population,country) values('Norwalk','California',102773,'USA');
Insert into places(city,region,population,country) values('Menifee','California',102527,'USA');
Insert into places(city,region,population,country) values('Vacaville','California',102386,'USA');
Insert into places(city,region,population,country) values('Wichita Falls','Texas',102316,'USA');
Insert into places(city,region,population,country) values('Davenport','Iowa',101724,'USA');
Insert into places(city,region,population,country) values('Quincy','Massachusetts',101636,'USA');
Insert into places(city,region,population,country) values('Chico','California',101475,'USA');
Insert into places(city,region,population,country) values('Lynn','Massachusetts',101253,'USA');
Insert into places(city,region,population,country) values('Lees Summit','Missouri',101108,'USA');
Insert into places(city,region,population,country) values('New Bedford','Massachusetts',101079,'USA');
Insert into places(city,region,population,country) values('Federal Way','Washington',101030,'USA');
Insert into places(city,region,population,country) values('Clinton','Michigan',100513,'USA');
Insert into places(city,region,population,country) values('Edinburg','Texas',100243,'USA');
Insert into places(city,region,population,country) values('Nampa','Idaho',100200,'USA');
Insert into places(city,region,population,country) values('İstanbul','Marmara Bölgesi',15462452,'TUR');              ### this part is to insert city,region and country values
Insert into places(city,region,population,country) values('Ankara','İç Anadolu Bölgesi',5663322,'TUR');
Insert into places(city,region,population,country) values('İzmir','Ege Bölgesi',4394694,'TUR');
Insert into places(city,region,population,country) values('Bursa','Marmara Bölgesi',3101833,'TUR');
Insert into places(city,region,population,country) values('Antalya','Akdeniz Bölgesi',2548308,'TUR');
Insert into places(city,region,population,country) values('Adana','Akdeniz Bölgesi',2258718,'TUR');
Insert into places(city,region,population,country) values('Konya','İç Anadolu Bölgesi',2250020,'TUR');
Insert into places(city,region,population,country) values('Şanlıurfa','Güneydoğu Anadolu Bölgesi',2118718,'TUR');
Insert into places(city,region,population,country) values('Gaziantep','Güneydoğu Anadolu Bölgesi',2101157,'TUR');
Insert into places(city,region,population,country) values('Kocaeli','Marmara Bölgesi',1997258,'TUR');
Insert into places(city,region,population,country) values('Mersin','Akdeniz Bölgesi',1868757,'TUR');
Insert into places(city,region,population,country) values('Diyarbakır','Güneydoğu Anadolu Bölgesi',1783431,'TUR');
Insert into places(city,region,population,country) values('Hatay','Akdeniz Bölgesi',1659320,'TUR');
Insert into places(city,region,population,country) values('Manisa','Ege Bölgesi',1450616,'TUR');
Insert into places(city,region,population,country) values('Kayseri','İç Anadolu Bölgesi',1421455,'TUR');
Insert into places(city,region,population,country) values('Samsun','Karadeniz Bölgesi',1356079,'TUR');
Insert into places(city,region,population,country) values('Balıkesir','Marmara Bölgesi',1240285,'TUR');
Insert into places(city,region,population,country) values('Kahramanmaraş','Akdeniz Bölgesi',1168163,'TUR');
Insert into places(city,region,population,country) values('Van','Doğu Anadolu Bölgesi',1149342,'TUR');
Insert into places(city,region,population,country) values('Aydın','Ege Bölgesi',1119084,'TUR');
Insert into places(city,region,population,country) values('Tekirdağ','Marmara Bölgesi',1081065,'TUR');
Insert into places(city,region,population,country) values('Sakarya','Marmara Bölgesi',1042649,'TUR');
Insert into places(city,region,population,country) values('Denizli','Ege Bölgesi',1040915,'TUR');
Insert into places(city,region,population,country) values('Muğla','Ege Bölgesi',1000773,'TUR');
Insert into places(city,region,population,country) values('Eskişehir','İç Anadolu Bölgesi',888828,'TUR');
Insert into places(city,region,population,country) values('Mardin','Güneydoğu Anadolu Bölgesi',854716,'TUR');
Insert into places(city,region,population,country) values('Trabzon','Karadeniz Bölgesi',811901,'TUR');
Insert into places(city,region,population,country) values('Malatya','Doğu Anadolu Bölgesi',806156,'TUR');
Insert into places(city,region,population,country) values('Ordu','Karadeniz Bölgesi',761400,'TUR');
Insert into places(city,region,population,country) values('Erzurum','Doğu Anadolu Bölgesi',758279,'TUR');
Insert into places(city,region,population,country) values('Afyonkarahisar','Ege Bölgesi',736912,'TUR');
Insert into places(city,region,population,country) values('Sivas','İç Anadolu Bölgesi',635889,'TUR');
Insert into places(city,region,population,country) values('Adıyaman','Güneydoğu Anadolu Bölgesi',632459,'TUR');
Insert into places(city,region,population,country) values('Batman','Güneydoğu Anadolu Bölgesi',620278,'TUR');
Insert into places(city,region,population,country) values('Tokat','Karadeniz Bölgesi',597861,'TUR');
Insert into places(city,region,population,country) values('Zonguldak','Karadeniz Bölgesi',591204,'TUR');
Insert into places(city,region,population,country) values('Elazığ','Doğu Anadolu Bölgesi',587960,'TUR');
Insert into places(city,region,population,country) values('Kütahya','Ege Bölgesi',576688,'TUR');
Insert into places(city,region,population,country) values('Osmaniye','Akdeniz Bölgesi',548556,'TUR');
Insert into places(city,region,population,country) values('Çanakkale','Marmara Bölgesi',541548,'TUR');
Insert into places(city,region,population,country) values('Şırnak','Doğu Anadolu Bölgesi',537762,'TUR');
Insert into places(city,region,population,country) values('Ağrı','Doğu Anadolu Bölgesi',535435,'TUR');
Insert into places(city,region,population,country) values('Çorum','Karadeniz Bölgesi',530126,'TUR');
Insert into places(city,region,population,country) values('Giresun','Karadeniz Bölgesi',448721,'TUR');
Insert into places(city,region,population,country) values('Isparta','Akdeniz Bölgesi',440304,'TUR');
Insert into places(city,region,population,country) values('Aksaray','İç Anadolu Bölgesi',423011,'TUR');
Insert into places(city,region,population,country) values('Yozgat','İç Anadolu Bölgesi',419095,'TUR');
Insert into places(city,region,population,country) values('Muş','Doğu Anadolu Bölgesi',411117,'TUR');
Insert into places(city,region,population,country) values('Edirne','Marmara Bölgesi',407763,'TUR');
Insert into places(city,region,population,country) values('Düzce','Karadeniz Bölgesi',395679,'TUR');
Insert into places(city,region,population,country) values('Kastamonu','Karadeniz Bölgesi',376377,'TUR');
Insert into places(city,region,population,country) values('Uşak','Ege Bölgesi',269433,'TUR');
Insert into places(city,region,population,country) values('Niğde','İç Anadolu Bölgesi',362071,'TUR');
Insert into places(city,region,population,country) values('Kırklareli','Marmara Bölgesi',361737,'TUR');
Insert into places(city,region,population,country) values('Bitls','Doğu Anadolu Bölgesi',350994,'TUR');
Insert into places(city,region,population,country) values('Rize','Karadeniz Bölgesi',344359,'TUR');
Insert into places(city,region,population,country) values('Amasya','Karadeniz Bölgesi',335494,'TUR');
Insert into places(city,region,population,country) values('Siirt','Güneydoğu Anadolu Bölgesi',331070,'TUR');
Insert into places(city,region,population,country) values('Bolu','Karadeniz Bölgesi',314802,'TUR');
Insert into places(city,region,population,country) values('Nevşehir','İç Anadolu Bölgesi',304962,'TUR');
Insert into places(city,region,population,country) values('Kars','Doğu Anadolu Bölgesi',284923,'TUR');
Insert into places(city,region,population,country) values('Bingöl','Doğu Anadolu Bölgesi',281768,'TUR');
Insert into places(city,region,population,country) values('Hakkari','Doğu Anadolu Bölgesi',280514,'TUR');
Insert into places(city,region,population,country) values('Kırıkkale','İç Anadolu Bölgesi',278703,'TUR');
Insert into places(city,region,population,country) values('Yalova','Marmara Bölgesi',276050,'TUR');
Insert into places(city,region,population,country) values('Burdur','Akdeniz Bölgesi',267092,'TUR');
Insert into places(city,region,population,country) values('Karaman','İç Anadolu Bölgesi',254919,'TUR');
Insert into places(city,region,population,country) values('Karabük','Karadeniz Bölgesi',243614,'TUR');
Insert into places(city,region,population,country) values('Kırşehir','İç Anadolu Bölgesi',243042,'TUR');
Insert into places(city,region,population,country) values('Erzincan','Doğu Anadolu Bölgesi',234431,'TUR');
Insert into places(city,region,population,country) values('Bilecik','Marmara Bölgesi',218717,'TUR');
Insert into places(city,region,population,country) values('Sinop','Karadeniz Bölgesi',216460,'TUR');
Insert into places(city,region,population,country) values('Iğdır','Doğu Anadolu Bölgesi',201314,'TUR');
Insert into places(city,region,population,country) values('Bartın','Karadeniz Bölgesi',198979,'TUR');
Insert into places(city,region,population,country) values('Çankırı','İç Anadolu Bölgesi',192428,'TUR');
Insert into places(city,region,population,country) values('Artvin','Karadeniz Bölgesi',169501,'TUR');
Insert into places(city,region,population,country) values('Kilis','Güneydoğu Anadolu Bölgesi',142792,'TUR');
Insert into places(city,region,population,country) values('Gümüşane','Karadeniz Bölgesi',141702,'TUR');
Insert into places(city,region,population,country) values('Ardahan','Doğu Anadolu Bölgesi',96161,'TUR');
Insert into places(city,region,population,country) values('Tunceli','Doğu Anadolu Bölgesi',83443,'TUR');
Insert into places(city,region,population,country) values('Bayburt','Karadeniz Bölgesi',81910,'TUR');
